### ISSUE TITLE
August 2020 Update causes a lua panic under certain conditions

### ISSUE THREAD

**Issue by Alydus** [Lexicality/gmod-sentry#9]
I haven't been able to investigate this very well myself as I'm on holiday, however the August 2020 update has caused a lua panic on our server during bootup (doesn't seem to occur 100% of the time)

![image](https://user-images.githubusercontent.com/11297569/90680055-1e81a100-e259-11ea-8cdd-65d8080e269d.png)

This patchnote imparticular is likely the root cause.

Hopefully this can be fixed, or a workaround found.

**Comment by Lexicality** [comment]
Interesting, are you able to find what error is output?

**Comment by Lexicality** [comment]
I just had a test and I can't replicate, I did discover that I'd broken master 2 weeks ago, did you update your code recently?

**Comment by Alydus** [comment]
![image](https://user-images.githubusercontent.com/11297569/90788665-f13afe80-e2fd-11ea-8b11-7b5d3fe68060.png)

@Lexicality I'm still not in a place to try and re-produce this at the moment, but I took this screenshot of what was repeating moments before the lua panic crash.

I did not update my code recently in the past two weeks, no.

**Comment by Lexicality** [comment]
Oh fun. I can put in some kind of crude protection against this, but I dunno if I'll be able to before the weekend. 

If you can find out why you don't have ISteamHTTP available that'd be useful, especially for me being able to reproduce this and stop it happening properly.

There's also probably an actual error buried deep within that infinite loop that's the cause of it in the first place.

**Comment by Lexicality** [comment]
Hi, sorry for the delay in getting this done.

This definitely fixes the problem, but it doesn't do it in a way I like. I'm going to see about tracking the errors we can't report during startup in another commit.
